### ISSUE TITLE
Newtype structs

### ISSUE THREAD

**Issue by torkleyy** [kvark/ron#15]
Newtype structs wrap an existing type:

```rust
struct NewType(i32);
```

---

I'm not sure here. Should it be `NewType(3)` with the name being optional? Or just `3`?

**Comment by kvark** [comment]
I believe it should be `NewType(3)`

**Comment by torkleyy** [comment]
I'm not sure. Serde says "serializers are encouraged to treat newtype structs as insignificant wrappers around the data they contain" (https://serde.rs/impl-deserializer.html).
