### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by torkleyy** [kvark/ron#16]
Enums look like

```rust
enum Enum {
    A,
    B(i32),
    C(f32, f32),
    D { x: f32, y: f32 },
}
```

---

Proposed strategy: Only serialize / deserialize the variant name and use the format we have for unit types, newtype wrappers, tuple structs and structs, respectively.

**Comment by kvark** [comment]
Could you elaborate on the proposal? Is this a clarification of how this should be done, or a proposal for an alternative?

**Comment by torkleyy** [comment]
This is how I currently implemented it and what I think it should be like. So just looking for opinions.
